### PR TITLE
structure each chapter with proper titles

### PR DESCRIPTION
**Pull request by kintininn**
chapter5 seems to be coming from a different book..?

### CODE REVIEW

**Comment by Oscar-Jin** [comment]
an interesting way to style each chapter

**Comment by kintininn** [comment]
yeah I think it is much more proper to add a title to each chapter :)

**Comment by Oscar-Jin** [comment]
yeah but I don't like it 👎

**Comment by kintininn** [comment]
I feel betrayed...

**Comment by kintininn** [comment]
(same person just messing around)

**Comment by Oscar-Jin** [comment]
(same person just messing around)

**Pull request closed without merging**
